canvas_fluttering_ribbon:
  enable: true
  mobile: true # false 手機端不顯示 true 手機端顯示
# # 點擊出現愛心
# click_heart:
#   enable: true
#   mobile: false
fireworks:
  enable: true
  zIndex: -1 # -1 or 9999
  mobile: false
# 美化頁面顯示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
# 加載動畫 Loading Animation
preloader:
  true
  # enable: false
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  # source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  # pace_css_url:

# 图片格式 background: url(http://xxxxxx.com/xxx.jpg)
# 顔色 background: '#49B202'
# 留空 显示白色
background: "#efefef"
# background: url(https://i.loli.net/2019/09/09/5oDRkWVKctx2b6A.png)

# 图片灯箱 - 点击放大
# Choose: fancybox / medium_zoom
lightbox: fancybox

index_img: https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
archive_img: https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
# Footer设置
since: 2022
footer_custom_text: Hi, welcome to my Xiaowen blog!
# footer是否显示图片背景(与top_img一致)
footer_bg: true

# 文章封面
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
    - https://gcore.jsdelivr.net/gh/volantis-x/cdn-wallpaper@1.0.0/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg

avatar:
  img: https://markdownhexo.oss-cn-hangzhou.aliyuncs.com/20170331090953_zUcaS.thumb.1000_0.jpeg
  # effect: true # 头像会一直转圈
# Inject the css and script (aplayer/meting)

aplayerInject:
  enable: true
  per_page: true
inject:
  head:
    - <link rel="stylesheet" href="/css/mouse.css">
  bottom:
    # 7427714271
    - <div class="aplayer no-destroy" data-id="7755841452" data-server="netease" data-type="playlist" data-fixed="true" data-mini="true" data-listFolded="false" data-order="random" data-lrctype="1" data-preload="none" data-autoplay="true" muted></div>
    - <script async src="https://npm.elemecdn.com/tzy-blog/lib/js/other/sakura.js"></script>
    - <script src="/js/sakura-toggle.js"></script>
pjax:
  enable: true
  exclude:

# social:
#   fab fa-github: https://github.com/xxxxx || Github
#   fas fa-envelope: mailto:xxxxxx@gmail.com || Email
wordcount:
  enable: true